name: 'Infrastructure as automation'
description: 'Upper automated terraform infrastructure orchestrator'
inputs:
  terragrunt_option:
    description: 'Terragrunt additional option'
    required: true
    default: --terragrunt-debug
  path:
    description: 'Which directory to use as context (the pwd will change to this path, relative to the root of your repository)'
    required: true
    default: ''
  gitconfig:
    description: 'Git config to use SSH redirections and provide authentication'
    required: false
    default: |
      [url "https://git@github.com"]
        insteadOf = "ssh://git@github.com"
      [url "https://YOUR_PERSONAL_ACCESS_TOKEN@github.com"]
        insteadOf = "ssh://private@github.com"
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - terragrunt
    - apply-all
    - --terragrunt-non-interactive
    - ${{ inputs.terragrunt_options }}