name: Unstable release channel (unstable.yml)

on:
  push:
    # paths:
    #   - "Dockerfile"
    #   - "docker-entrypoint.sh"
    branches:
      - main

jobs:

  push_to_registry:
  
      name: Push Docker image to GitHub Packages
      runs-on: ubuntu-20.04

      steps:

        - name: Check out the reposiotry
          uses: actions/checkout@v2
          
        - name: Build Image
          id: build-image
          uses: redhat-actions/buildah-build@v1
          with:
            image: ghcr.io/metacron/turbojet
            tags: unstable latest
            dockerfiles: |
              ./Dockerfile

        - name: Push To Quay
          id: push-to-quay
          uses: redhat-actions/push-to-registry@v1
          with:
            image: ${{ steps.build-image.outputs.image }}
            tags: ${{ steps.build-image.outputs.tags }}
            registry: ghcr.io
            username: ${{ secrets.GH_PAT_USER }}
            password: ${{ secrets.GH_PAT }}