name: Unstable release channel (unstable.yml)

on:
  push:
    # paths:
    #   - "Dockerfile"
    #   - "docker-entrypoint.sh"
    branches:
      - main

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: turbojet
  IMAGE_TAGS: latest unstable

jobs:

  push_to_registry:
  
      name: Push container image to GitHub Packages
      runs-on: ubuntu-20.04

      steps:

        - name: Check out the reposiotry
          uses: actions/checkout@v2
          
        - name: Build Image
          id: build-image
          uses: redhat-actions/buildah-build@main
          with:
            image: ${{ env.IMAGE_NAME }}
            tags: ${{ env.IMAGE_TAGS }}
            dockerfiles: |
              ./Dockerfile

        - name: Push To Registry
          id: push-to-registry
          uses: redhat-actions/push-to-registry@main
          with:
            image: ${{ steps.build-image.outputs.image }}
            tags: ${{ steps.build-image.outputs.tags }}
            registry: ${{ env.IMAGE_REGISTRY }}/${{ secrets.REGISTRY_USER }}
            username: ${{ secrets.REGISTRY_USER }}
            password: ${{ secrets.REGISTRY_PASSWORD }}