name: Unstable release channel (unstable.yml)

on:
  push:
    paths:
      - "Dockerfile"
      - "docker-entrypoint.sh"
    branches:
      - main

jobs:

  push_to_registry:
  
      name: Push Docker image to GitHub Packages
      runs-on: ubuntu-20.04

      steps:

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to GitHub Packages
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ secrets.GH_PAT_USER }}
            password: ${{ secrets.GH_PAT }}

        - name: Check out the reposiotry
          uses: actions/checkout@v2

        # Configuration requirement:
        # https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/enabling-improved-container-support
        - name: Push to GitHub Packages
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            context: "."
            platforms: linux/amd64,linux/arm64
            tags: ghcr.io/metacron/turbojet:unstable,ghcr.io/metacron/turbojet:latest

        - name: Image digest (metacron/turbojet:unstable)
          run: echo ${{ steps.docker_build.outputs.digest }}